### ISSUE TITLE
last working version?

### ISSUE THREAD

**Issue by priamai** [haseeb-heaven/LangChain-Coder#6]
Hi there,
I run the main version via streamlit and there are multiple issues/bugs.
Are you still maintaining it or is there another branch I should test?
Cheers.

**Comment by haseeb-heaven** [comment]
Hi.
There are two branches.

1. Streamlit : https://github.com/haseeb-heaven/LangChain-Coder/tree/streamlit
2. Main: https://github.com/haseeb-heaven/LangChain-Coder/tree/master

The one thats updated is one **Streamlit** branch.

**Comment by haseeb-heaven** [comment]
> Thanks testing. I like the way you used LiteLLM so I can switch the backends easily.

Yes LiteLLM is great way to access all LLM easily

**Comment by priamai** [comment]
Okay @haseeb-heaven let's do some debugging, I did a checkout of the streamlit branch.
When I run I get this errors:

You can now view your Streamlit app in your browser.

```
  Network URL: http://192.168.2.17:8501
  External URL: http://51.19.21.231:8501

/home/robomotic/.pyenv/versions/3.11.6/envs/langcoder/lib/python3.11/site-packages/langchain/__init__.py:34: UserWarning: Importing LLMChain from langchain root module is no longer supported. Please use langchain.chains.LLMChain instead.
  warnings.warn(
/home/robomotic/.pyenv/versions/3.11.6/envs/langcoder/lib/python3.11/site-packages/langchain/__init__.py:34: UserWarning: Importing PromptTemplate from langchain root module is no longer supported. Please use langchain.prompts.PromptTemplate instead.
  warnings.warn(
2023-12-04 23:53:55.556 Uncaught app exception
Traceback (most recent call last):
  File "/home/robomotic/.pyenv/versions/3.11.6/envs/langcoder/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/media/robomotic/bumbledisk/github/LangChain-Coder/script.py", line 466, in <module>
    main()
  File "/media/robomotic/bumbledisk/github/LangChain-Coder/script.py", line 248, in main
    if len(st.session_state.code_input) == 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

```
The first two warnings are easy to fix, the NoneType happens I believe simply because the input box is undefined at the beginning, I think a quick fix is to check is is None first then check for length.

![image](https://github.com/haseeb-heaven/LangChain-Coder/assets/57333254/235dfb25-0026-4d84-9ff0-41d179c1c02f)

**Comment by priamai** [comment]
Second: I noticed even when I put the Open API KEY in the env variable is not displayed in the Open AI settings.
Line 26:         openai.api_key = api_key or os.getenv("OPENAI_API_KEY")

However field is not updated:

![image](https://github.com/haseeb-heaven/LangChain-Coder/assets/57333254/ef3c121d-3c38-4964-a089-a5885e24274b)

**Comment by priamai** [comment]
Third on line 154, there is a duplicated entry, easy fix just remove it:

model_options_openai = ["gpt-4", "gpt-4-0613", "gpt-4-32k", "gpt-4-32k-0613", "gpt-3.5-turbo", "gpt-3.5-turbo", "gpt-3.5-turbo-16k", "gpt-3.5-turbo-0613", "gpt-3.5-turbo-16k-0613", "gpt-3.5-turbo-0301", "text-davinci-003"]


![image](https://github.com/haseeb-heaven/LangChain-Coder/assets/57333254/f660610b-8838-42a0-a83a-381db5cbb02a)

**Comment by priamai** [comment]
When I press CTRL+ENTER nothing happens:

![image](https://github.com/haseeb-heaven/LangChain-Coder/assets/57333254/e96f1cc3-5b4a-4f41-9c55-4dda0591bd41)

It still triggers the NoneType exception.

**Comment by haseeb-heaven** [comment]
I think you missed the OpenAI key as Input there.
If you think issue is not resolved then create PR on that branch I will take a look.
Thanks

**Comment by priamai** [comment]
> I think you missed the OpenAI key as Input there. If you think issue is not resolved then create PR on that branch I will take a look. Thanks

It was on purpose to verify if the streamlit app was using dotenv to load it from the .env file which it doesn't. I can put a few print statements to see why it fails to set the field.

**Comment by haseeb-heaven** [comment]
> Second: I noticed even when I put the Open API KEY in the env variable is not displayed in the Open AI settings. Line 26: openai.api_key = api_key or os.getenv("OPENAI_API_KEY")
> 
> However field is not updated:
> 
> ![image](https://private-user-images.githubusercontent.com/57333254/287876639-ef3c121d-3c38-4964-a089-a5885e24274b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MDE5NTIsIm5iZiI6MTcwMTgwMTY1MiwicGF0aCI6Ii81NzMzMzI1NC8yODc4NzY2MzktZWYzYzEyMWQtM2MzOC00OTY0LWEwODktYTU4ODVlMjQyNzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE4NDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NWRhMDlmYTljMGZjZGIzMzM5MmRiOTFkOGNiMTM4NzlkYWJmZTE5MTA4MWI3ZGU2MDFhNzMxOTZiMmU3ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8bN-d9cedxi62jdsOycdn3jaeKb4O56QuibZR-nXEgI)

It won't be updated here and just the textbox to provide the key or it will take default from **.env** file

**Comment by haseeb-heaven** [comment]
> > I think you missed the OpenAI key as Input there. If you think issue is not resolved then create PR on that branch I will take a look. Thanks
> 
> It was on purpose to verify if the streamlit app was using dotenv to load it from the .env file which it doesn't. I can put a few print statements to see why it fails to set the field.

Because I never added that feature that's why.

**Comment by haseeb-heaven** [comment]
Can you create a new issue with all logs and screenshots so its easy for me to take a look at it.
